version: '3.8'

services:
  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - python-processor
    networks:
      - app-network

  python-processor:
    build:
      context: ./python-processor
      dockerfile: Dockerfile
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge